#version: '3.9'

services:
  db:
    image: postgres:17.4-alpine
    container_name: zephyr_db
    restart: always
    environment:
      POSTGRES_USER: zephyr_admin
      POSTGRES_PASSWORD: password99!
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5437:5432"
    networks:
      - db

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    environment:
      - REDIS_PASSWORD=3F(c30;r]58;hs0+e1fo
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s


networks:
  db:
    driver: bridge

volumes:
  db:
  cache:
