#version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: zephyr_db
    restart: always
    environment:
      POSTGRES_USER: zephyr_admin
      POSTGRES_PASSWORD: password99!
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5437:5432"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
