ktor:
    application:
        modules:
            - com.shoejs.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
postgres:
  url: "jdbc:postgresql://localhost:5437/zephyr"
  driver: "org.postgresql.Driver"
  user: zephyr_admin
  password: password99!
